ur5_controller:
  ros__parameters:
    type: ros2_impedance_controller/CartesianController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    base_link: base_link
    interaction_link: ee_link
    ft_sensor_topic: end_effector_ft_sensor
    stiffness: [200.0, 800.0, 800.0, 120.0, 120.0, 120.0]
    taskspace_mass: 20.0
    # stiffness: [400.0, 400.0, 400.0, 70.0, 70.0, 40.0]  # TODO: tuning
    # damping: [134.16, 134.16, 134.16, 15.086, 15.086, 15.086]
    # taskspace_mass: 0.0
    urdf_package: ros2_descriptions
    urdf_relative_path: /description/urdf/ur5.description.urdf.xacro
    visualize_reference: true

spot_leg_controller:
  ros__parameters:
    type: ros2_impedance_controller/CartesianController
    joints:
      - fl_hipx
      - fl_hipy
      - fl_knee
    base_link: leg_support
    interaction_link: fl_foot
    stiffness: [400.0, 400.0, 800.0, 0.0, 0.0, 0.0]
    damping: [43.0, 43.0, 90.0, 0.0, 0.0, 0.0]
    taskspace_mass: 0.0
    urdf_package: ros2_descriptions
    urdf_relative_path: /description/urdf/spot_leg.description.urdf.xacro
    visualize_reference: true

hyl_controller:
  ros__parameters:
    type: ros2_impedance_controller/BasicCartesianController
    joints:
      - hfe_joint
      - kfe_joint
    base_link: trunk
    interaction_link: foot
    stiffness: [400.0, 0.0, 800.0, 0.0, 0.0, 0.0]
    damping: [43.0, 0.0, 90.0, 0.0, 0.0, 0.0]
    urdf_package: ros2_descriptions
    urdf_relative_path: /description/urdf/hyl.description.urdf.xacro
    visualize_reference: true

mpc_controller:
  ros__parameters:
    type: ros2_impedance_controller/MPCIController
    joints:
      - hfe_joint
      - kfe_joint
    base_link: trunk
    interaction_link: foot
    stiffness: [400.0, 0.0, 800.0, 0.0, 0.0, 0.0]
    damping: [43.0, 0.0, 90.0, 0.0, 0.0, 0.0]
    urdf_package: ros2_descriptions
    urdf_relative_path: /description/urdf/hyl.description.urdf.xacro
    visualize_reference: true
    torque_max: 150.0
    timestep: 0.001
    horizon: 35  # working up-to 60

spot_controller:
  ros__parameters:
    type: ros2_impedance_controller/CartesianController
    joints:
      - fl_hipx
      - fl_hipy
      - fl_knee
    base_link: body
    interaction_link: fl_foot
    # TBD: Whole-Body Controller
    stiffness: [700.0, 700.0, 1000.0, 0.0, 0.0, 0.0]
    damping: [52.0, 52.0, 63.0, 0.0, 0.0, 0.0]
    taskspace_mass: 0.0
    urdf_package: ros2_descriptions
    urdf_relative_path: /description/urdf/spot.description.urdf.xacro
    visualize_reference: true
