// Copyright (c) 2026, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROS2_IMPEDANCE_CONTROLLER__BASIC_CARTESIAN_CONTROLLER_HPP_
#define ROS2_IMPEDANCE_CONTROLLER__BASIC_CARTESIAN_CONTROLLER_HPP_

#include <memory>
#include "pinocchio/algorithm/cholesky.hpp"
#include "ros2_impedance_controller/impedance_controller_base.hpp"
// auto-generated by generate_parameter_library
#include "ros2_impedance_controller/cartesian_controller_parameters.hpp"

namespace ros2_impedance_controller
{
/**
 * \brief Basic Cartesian impedance controller with only
 * gravity compensation and PD impedance.
 */
class BasicCartesianController : public ImpedanceControllerBase
{
public:
  BasicCartesianController();

protected:
  void declare_parameters() override;

  controller_interface::CallbackReturn read_parameters() override;

  controller_interface::CallbackReturn update_effort_commands() override;

  void custom_configuration() override;

  void custom_activation() override;

  /**
   * @brief Port-Hamiltonian diagnostics with:
   * 1. Joint space control power;
   * 2. Joint space total minus control power;
   * 3. Interaction power;
   * 4. Impedance Hamiltonian;
   * 5. Impedance Hamiltonian I/O power;
   * 6. Model-based interaction power.
   */
  void publish_status() override;

  /**
   * @brief Compute Cartesian impedance Hamiltonian function
   */
  void compute_hamiltonian();

  /**
   * @brief Compute Operational Space Inertia Matrix (OSIM).
   * Matrix updated value is stored in `actual_inertia_`.
   */
  void compute_osim();

  /**
   * @brief Estimate the operational space inertia matrix diagonal
   */
  void estimate_inertia_diagonal();

  std::shared_ptr<::cartesian_controller::ParamListener> param_listener_;
  ::cartesian_controller::Params params_;

  rclcpp::Clock::SharedPtr steady_clock_;
  // `update_effort_commands` start
  rclcpp::Time update_start_;
  // `update_effort_commands` end
  rclcpp::Time update_end_;

  /* Port-Hamiltonian variables */
  // Impedance Hamiltonian function value
  double hamiltonian_{0};
  double hamiltonian_last_{0};
  double hamiltonian_filtered_{0};
  double hamiltonian_derivative_{0};
  // Expected impedance input (u)
  Vector6d impedance_expected_input_;

  // End effector task space twist derivative
  Vector6d accel_deviation_;

  // Command terms
  VectorXd tau_desired_;

  Matrix6d accel_delta_;
  Vector6d accel_last_;
  Vector6d wrench_delta_;
  Vector6d osim_diagonal_;  // OSIM diagonal estimate
};

}  // namespace ros2_impedance_controller

#endif  // ROS2_IMPEDANCE_CONTROLLER__BASIC_CARTESIAN_CONTROLLER_HPP_
