// Copyright (c) 2025, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROS2_IMPEDANCE_CONTROLLER__CARTESIAN_CONTROLLER_HPP_
#define ROS2_IMPEDANCE_CONTROLLER__CARTESIAN_CONTROLLER_HPP_

#include <memory>

#include "ros2_impedance_controller/impedance_controller_base.hpp"
// auto-generated by generate_parameter_library
#include "ros2_impedance_controller/cartesian_controller_parameters.hpp"

namespace ros2_impedance_controller
{
using ReferenceType = kinematic_pose_msgs::msg::KinematicPose;

/**
 * \brief Cartesian impedance controller for articulated robots.
 */
class CartesianController : public ImpedanceControllerBase
{
public:
  CartesianController();

protected:
  void declare_parameters() override;

  controller_interface::CallbackReturn read_parameters() override;

  controller_interface::CallbackReturn update_effort_commands() override;

  void custom_configuration() override;

  void custom_activation() override;

  /**
   * @brief Port-Hamiltonian diagnostics with:
   * 1. Joint space control power;
   * 2. Joint space total minus control power;
   * 3. Interaction power;
   * 4. Impedance Hamiltonian;
   * 5. Impedance Hamiltonian I/O power;
   * 6. Model-based interaction power.
   */
  void publish_status() override;

  /**
   * @brief Impedance space diagnostics with pose_deviation_, twist_deviation_,
   * and interaction wrench estimation.
   */
  void zspace_diagnostics();

  /**
   * @brief Phase space diagnostics.
   */
  void phase_space_diagnostics();

  /**
   * @brief Compute Cartesian impedance Hamiltonian function
   */
  void compute_hamiltonian();

  std::shared_ptr<::cartesian_controller::ParamListener> param_listener_;
  ::cartesian_controller::Params params_;

  // Interaction force/torque subscriber
  rclcpp::Subscription<geometry_msgs::msg::Wrench>::SharedPtr int_subscriber_;

  bool inertia_shaping_;

  /* Port-Hamiltonian variables */
  // Impedance power
  double impedance_power_{0};
  // Impedance Hamiltonian function value
  double hamiltonian_{0};
  double hamiltonian_last_{0};
  double hamiltonian_filtered_{0};
  double hamiltonian_derivative_{0};
  // Expected impedance input (u)
  Vector6d impedance_expected_input_;

  // Desired impedance wrench [forces, torques].T
  Vector6d impedance_wrench_;
  // Interaction wrench [forces, torques].T
  Vector6d sensor_wrench_;
  // Interaction wrench estimation
  Vector6d estimated_wrench_;

  // Command terms
  VectorXd twist_compensation_;
  VectorXd accel_feedforward_;
  VectorXd impedance_torques_;
  VectorXd tau_desired_;

  Matrix6Xd jacobian_derivative_;
  Eigen::MatrixXd jacobian_pinv_;
  Eigen::MatrixXd jacobianT_pinv_;
  Eigen::MatrixXd jsim_jpinv_dj_;
  Eigen::MatrixXd jsim_jpinv_;
};

}  // namespace ros2_impedance_controller

#endif  // ROS2_IMPEDANCE_CONTROLLER__CARTESIAN_CONTROLLER_HPP_
