// Copyright (c) 2026, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROS2_IMPEDANCE_CONTROLLER__MPCIC_CONTROLLER_HPP_
#define ROS2_IMPEDANCE_CONTROLLER__MPCIC_CONTROLLER_HPP_

#include <memory>
#include <qpOASES.hpp>

#include "ros2_impedance_controller/impedance_controller_base.hpp"
#include "ros2_impedance_controller/taskspace_predictor.hpp"
// auto-generated by generate_parameter_library
#include "ros2_impedance_controller/mpcic_parameters.hpp"

namespace ros2_impedance_controller
{
// Dynamic size row-major storage Eigen matrix,
// easing qpOASES C-style access to matrices. Use m.data()
typedef Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> MatrixXr;

/**
 * \brief Model Predictive Cartesian Impedance Controller.
 *
 * This class implement the Model Predictive Cartesian Impedance Control (MPCIC), with
 * cost function formulation centered on the impedance dynamics.
 */
class MPCIController : public ImpedanceControllerBase
{
public:
  MPCIController();

protected:
  void declare_parameters() override;

  controller_interface::CallbackReturn read_parameters() override;

  controller_interface::CallbackReturn update_effort_commands() override;

  void custom_configuration() override;

  void custom_activation() override;

  /**
   * @brief Port-Hamiltonian diagnostics with:
   * 1. Joint space control power;
   * 2. Joint space total minus control power;
   * 3. Interaction power;
   * 4. Impedance Hamiltonian;
   * 5. Impedance Hamiltonian I/O power;
   * 6. Model-based interaction power.
   */
  void publish_status() override;

  /**
   * @brief Phase space diagnostics.
   */
  void phase_space_diagnostics();

  /**
   * @brief Compute Cartesian impedance Hamiltonian function
   */
  void compute_hamiltonian();

  std::shared_ptr<::mpcic_controller::ParamListener> param_listener_;
  ::mpcic_controller::Params params_;

  std::shared_ptr<TaskspacePredictor> predictor_;
  bool debug_{false};

  double timestep_;
  uint8_t horizon_;
  // Online active-set strategy for QPs with varying matrices
  std::shared_ptr<qpOASES::SQProblem> sqproblem_;
  qpOASES::Options sqp_options_;  // QP Options
  qpOASES::returnValue sqp_ret_;  // QP return value
  int sqp_status_;                // QP simple status (see docs)
  int constraints_dim_;           // constraints space dimension (nC): DoF
  int action_dim_;                // action space dimension (nV): DoF*N

  MatrixXr H_qp_;    // QP Hessian matrix
  MatrixXr g_qp_;    // QP gradient vector
  MatrixXr A_qp_;    // QP constraint matrix
  MatrixXr lb_qp_;   // QP lower bound vector
  MatrixXr ub_qp_;   // QP upper bound vector
  MatrixXr lbA_qp_;  // QP lower constraints' bound vector
  MatrixXr ubA_qp_;  // QP upper constraints' bound vector
  int max_wsr_;      // QP max number of working set recalculations

  MatrixXr Q_weight_;  // cost function norm weight matrix

  /* Port-Hamiltonian variables */
  // Impedance Hamiltonian function value
  double hamiltonian_{0};
  double hamiltonian_last_{0};
  double hamiltonian_filtered_{0};
  double hamiltonian_derivative_{0};

  // Desired impedance wrench [forces, torques].T
  Vector6d impedance_wrench_;
  // Interaction wrench estimation
  Vector6d estimated_wrench_;

  // Command terms
  VectorXd tau_desired_;

  Eigen::MatrixXd jacobian_pinv_;
  Eigen::MatrixXd jacobianT_pinv_;
};

}  // namespace ros2_impedance_controller

#endif  // ROS2_IMPEDANCE_CONTROLLER__MPCIC_CONTROLLER_HPP_
