// Copyright (c) 2026, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROS2_IMPEDANCE_CONTROLLER__MPCIC_CONTROLLER_HPP_
#define ROS2_IMPEDANCE_CONTROLLER__MPCIC_CONTROLLER_HPP_

#include <memory>
#include <qpOASES.hpp>

#include "ros2_impedance_controller/impedance_controller_base.hpp"
#include "ros2_impedance_controller/taskspace_predictor.hpp"
// auto-generated by generate_parameter_library
#include "ros2_impedance_controller/mpcic_parameters.hpp"

namespace ros2_impedance_controller
{
// Dynamic size row-major storage Eigen matrix,
// easing qpOASES C-style access to matrices. Use m.data()
typedef Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> MatrixXr;

/**
 * \brief Model Predictive Cartesian Impedance Controller.
 *
 * This class implement the Model Predictive Cartesian Impedance Control (MPCIC), with
 * cost function formulation centered on the impedance dynamics.
 */
class MPCIController : public ImpedanceControllerBase
{
public:
  MPCIController();

protected:
  void declare_parameters() override;

  controller_interface::CallbackReturn read_parameters() override;

  controller_interface::CallbackReturn update_effort_commands() override;

  void custom_configuration() override;

  void custom_activation() override;

  /**
   * @brief Port-Hamiltonian diagnostics with:
   * 1. Joint space control power;
   * 2. Joint space total minus control power;
   * 3. Interaction power;
   * 4. Impedance Hamiltonian;
   * 5. Impedance Hamiltonian I/O power;
   * 6. Model-based interaction power.
   */
  void publish_status() override;

  /**
   * @brief assemble the `L` horizon `stack`
   */
  void assemble_Ln();

  void assemble_Aqp();

  void update_taskstates();

  void update_references();

  /**
   * @brief Check non-empty reference message
   *
   * @return true if valid, and false if empty.
   */
  bool validate_reference();

  void update_Ln(Eigen::MatrixXd Cn);

  void update_QP();

  std::shared_ptr<::mpcic_controller::ParamListener> param_listener_;
  ::mpcic_controller::Params params_;

  std::shared_ptr<TaskspacePredictor> predictor_;
  bool debug_{true};

  uint8_t horizon_;
  // Online Active-Set strategy for QPs with varying matrices
  std::shared_ptr<qpOASES::SQProblem> sqproblem_;
  qpOASES::Options sqp_options_;  // QP Options
  qpOASES::returnValue sqp_ret_;  // QP return value
  int sqp_status_;                // QP simple status (see docs)
  uint constraints_dim_;          // constraints space dimension (nC): DoF
  uint action_dim_;               // action space dimension (nV): DoF*N

  MatrixXr H_qp_;           // QP Hessian matrix
  MatrixXr g_qp_;           // QP gradient vector
  MatrixXr A_qp_;           // QP constraint matrix
  Eigen::VectorXd lb_qp_;   // QP lower bound vector
  Eigen::VectorXd ub_qp_;   // QP upper bound vector
  Eigen::VectorXd lbA_qp_;  // QP lower constraints' bound vector
  Eigen::VectorXd ubA_qp_;  // QP upper constraints' bound vector
  Eigen::VectorXd du_max_;  // QP maximum action delta (u_{k+1} - u_{k})
  int nWSR_;                // QP max number of working set recalculations (nWSR)
  int nWSR_qp_;             // QP WSR for in place output in `hotstart` method
  double cputime_;          // QP maximum allowed CPU time in seconds
  double cputime_qp_;       // CPU time spent for QP solution (or to perform nWSR iterations)

  /**
   * @note Cost function is: min_{u} (V*u + b)^T*Q*(V*u + b) + u^T*R*u,
   * where:
   * b := L*F*x_0 - Z*x_{d} - J*g(q)
   * V := L*G + J
   */

  Eigen::MatrixXd V_qp_;  // `V` multiplies `u` in the cost function
  Eigen::VectorXd b_qp_;  // bias vector `b` in the cost function
  Eigen::MatrixXd L_qp_;  // action space projection along the horizon
  Eigen::MatrixXd Z_qp_;  // impedance gains along the horizon
  Eigen::MatrixXd Q_qp_;  // task space dynamics error norm weight
  Eigen::MatrixXd R_qp_;  // joint space torque `stack` norm weight
  Eigen::VectorXd u_qp_;  // QP solution as Eigen::Vector

  Eigen::Matrix<double, kStateSpaceDim, 1> task_states_;  // task space state vector
  Eigen::VectorXd task_desired_;     // impedance setpoint state (x_{d}) along the horizon
  Eigen::Quaterniond quat_desired_;  // x_{d} pose quaternion
  Eigen::Vector3d log3_desired_;     // x_{d} pose quaternion log3 map

  // Command terms
  Eigen::VectorXd tau_desired_;

  size_t dof_;
};

}  // namespace ros2_impedance_controller

#endif  // ROS2_IMPEDANCE_CONTROLLER__MPCIC_CONTROLLER_HPP_
