// Copyright (c) 2026, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROS2_IMPEDANCE_CONTROLLER__NONLINEAR_CARTESIAN_CONTROLLER_HPP_
#define ROS2_IMPEDANCE_CONTROLLER__NONLINEAR_CARTESIAN_CONTROLLER_HPP_

#include <memory>

#include "pinocchio/algorithm/cholesky.hpp"
#include "ros2_impedance_controller/impedance_controller_base.hpp"
// auto-generated by generate_parameter_library
#include "ros2_impedance_controller/nonlinear_controller_parameters.hpp"

namespace ros2_impedance_controller
{
/**
 * \brief Basic Cartesian impedance controller with only
 * gravity compensation and PD impedance.
 */
class NonlinearCartesianController : public ImpedanceControllerBase
{
public:
  NonlinearCartesianController();

protected:
  void declare_parameters() override;

  controller_interface::CallbackReturn read_parameters() override;

  controller_interface::CallbackReturn update_effort_commands() override;

  void custom_configuration() override;

  void custom_activation() override;

  /**
   * @brief Port-Hamiltonian diagnostics with:
   * 1. Joint space control power;
   * 2. Joint space total minus control power;
   * 3. Interaction power;
   * 4. Impedance Hamiltonian;
   * 5. Impedance Hamiltonian I/O power;
   * 6. Model-based interaction power.
   */
  void publish_status() override;

  /**
   * @brief Compute Cartesian impedance Hamiltonian function
   */
  void compute_hamiltonian();

  /**
   * @brief Compute and update Cartesian Stiffness
   *
   * This nonlinear sitffness saturates decreasing the effective stiffness
   * for high deviations (e). To smoothing collisions, it does also decrease
   * the sitffness for high deviation derivative (\dot{e}). Both nonlinearities
   * are continuous.
   */
  void update_stiffness();

  /**
   * @brief Compute and update Cartesian Damping
   *
   * Use the closed-loop joint space divergence to ensure
   * the system is dissipative. If the flow in phase space
   * is contracting, i.e. Div F < 0, the system is dissipative.
   *
   * Ref.: Greiner, W. Systems of Particles and Hamiltonian Dynamics, pg. 465
   */
  void update_damping();

  std::shared_ptr<::nonlinear_controller::ParamListener> param_listener_;
  ::nonlinear_controller::Params params_;

  rclcpp::Clock::SharedPtr steady_clock_;
  // `update_effort_commands` start
  rclcpp::Time update_start_;
  // `update_effort_commands` end
  rclcpp::Time update_end_;

  /* Port-Hamiltonian variables */
  // Impedance Hamiltonian function value
  double hamiltonian_{0};
  double hamiltonian_last_{0};
  double hamiltonian_filtered_{0};
  double hamiltonian_derivative_{0};
  // Expected impedance input (u)
  Vector6d impedance_expected_input_;

  // Desired impedance wrench [forces, torques].T
  Vector6d impedance_wrench_;
  // Interaction wrench estimation
  Vector6d estimated_wrench_;
  // End effector task space twist derivative
  Vector6d accel_deviation_;

  // Nonlinear
  // Nominal stiffness
  DiagonalMatrix6d nominal_stiffness_;
  // Nominal damping
  DiagonalMatrix6d nominal_damping_;
  // Sigmoid-based spring saturation
  double spring_force_limit_{1.0};

  // Phase space divergence
  double divergence_{0.0};

  // Command terms
  VectorXd tau_desired_;

  Eigen::MatrixXd jacobian_dt_;
  Eigen::MatrixXd jacobian_pinv_;
  Eigen::MatrixXd jacobianT_pinv_;
  Eigen::MatrixXd jsim_jpinv_;
  Eigen::MatrixXd jsim_jpinv_dj_;
};

}  // namespace ros2_impedance_controller

#endif  // ROS2_IMPEDANCE_CONTROLLER__NONLINEAR_CARTESIAN_CONTROLLER_HPP_
