// Copyright (c) 2025, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROS2_IMPEDANCE_CONTROLLER__ROS2_IMPEDANCE_CONTROLLER_HPP_
#define ROS2_IMPEDANCE_CONTROLLER__ROS2_IMPEDANCE_CONTROLLER_HPP_

#include <eigen3/Eigen/Dense>

#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "pinocchio/algorithm/frames.hpp"
#include "pinocchio/algorithm/geometry.hpp"
#include "pinocchio/algorithm/jacobian.hpp"
#include "pinocchio/algorithm/joint-configuration.hpp"
#include "pinocchio/algorithm/rnea.hpp"
#include "pinocchio/collision/broadphase.hpp"
#include "pinocchio/parsers/urdf.hpp"

#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/pose.hpp"
#include "hardware_interface/loaned_command_interface.hpp"
#include "hardware_interface/loaned_state_interface.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"

// auto-generated by generate_parameter_library
#include "ros2_impedance_controller/ros2_impedance_controller_parameters.hpp"

namespace ros2_impedance_controller
{
using ReferenceType = geometry_msgs::msg::Pose;

using DiagonalMatrix6d = Eigen::DiagonalMatrix<double, 6>;
using Vector6d = Eigen::Matrix<double, 6, 1>;

enum InterfaceType : uint8_t
{
  POSITION,
  VELOCITY,
  EFFORT
};

std::unordered_map<std::string, InterfaceType> InterfaceMap = {
  {hardware_interface::HW_IF_POSITION, InterfaceType::POSITION},
  {hardware_interface::HW_IF_VELOCITY, InterfaceType::VELOCITY},
  {hardware_interface::HW_IF_EFFORT, InterfaceType::EFFORT},
};

/**
 * \brief Cartesian Impedance Controller for Manipulators.
 */
class ImpedanceController : public controller_interface::ControllerInterface
{
public:
  ImpedanceController();

  ~ImpedanceController() = default;

  // Indicating which command interfaces are to be claimed.
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  // Indicating which state interfaces are to be claimed.
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

protected:
  bool configure_robot_model();

  bool update_robot();

  void declare_parameters();

  controller_interface::CallbackReturn read_parameters();

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

private:
  void robot_description_param_cb(std::shared_future<std::vector<rclcpp::Parameter>> future);

  std::shared_ptr<rclcpp::AsyncParametersClient> parameters_client_;
  std::string robot_urdf_;

  std::vector<const hardware_interface::LoanedStateInterface *> position_interfaces_;
  std::vector<const hardware_interface::LoanedStateInterface *> velocity_interfaces_;
  std::vector<const hardware_interface::LoanedStateInterface *> effort_interfaces_;
  std::vector<hardware_interface::LoanedCommandInterface *> effort_command_interfaces_;

  bool has_effort_states_{true};
  bool debug_gravity_{true};

  double update_rate_;

  // Kinematics parameters
  std::string base_link_;
  std::string interaction_link_;
  size_t degrees_of_freedom_{1};

  // Task space stiffness
  DiagonalMatrix6d taskspace_stiffness_;
  // Task space damping
  DiagonalMatrix6d taskspace_damping_;

  // Robot state vectors
  Eigen::VectorXd robot_positions_;
  Eigen::VectorXd robot_velocities_;
  Eigen::VectorXd robot_efforts_;

  // Controller effort command vector
  Eigen::VectorXd effort_commands_;

  pinocchio::Model robot_model_;
  std::shared_ptr<pinocchio::Data> robot_data_ptr_;

  // Controller Reference Subscriber
  realtime_tools::RealtimeBuffer<std::shared_ptr<ReferenceType>> rt_reference_ptr_;
  rclcpp::Subscription<ReferenceType>::SharedPtr reference_subscriber_;
};

}  // namespace ros2_impedance_controller

#endif  // ROS2_IMPEDANCE_CONTROLLER__ROS2_IMPEDANCE_CONTROLLER_HPP_
