// Copyright (c) 2025, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROS2_IMPEDANCE_CONTROLLER__ROS2_IMPEDANCE_CONTROLLER_HPP_
#define ROS2_IMPEDANCE_CONTROLLER__ROS2_IMPEDANCE_CONTROLLER_HPP_

#include <eigen3/Eigen/Dense>

#include <memory>
#include <string>
#include <vector>

#include <dart/dart.hpp>
#include <dart/utils/urdf/DartLoader.hpp>
#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/pose.hpp"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"

// auto-generated by generate_parameter_library
#include "ros2_impedance_controller/ros2_impedance_controller_parameters.hpp"

namespace ros2_impedance_controller
{
using ReferenceType = geometry_msgs::msg::Pose;
using Matrix6d = Eigen::Matrix<double, 6, 6>;
using Vector6d = Eigen::Matrix<double, 6, 1>;

/**
 * \brief Cartesian Impedance Controller for Manipulators.
 */
class ImpedanceController : public controller_interface::ControllerInterface
{
public:
  ImpedanceController();

  ~ImpedanceController() = default;

  // Indicating which command interfaces are to be claimed.
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  // Indicating which state interfaces are to be claimed.
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

protected:
  bool configure_robot_model();

  bool update_robot_model_states();

  void declare_parameters();

  controller_interface::CallbackReturn read_parameters();

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

private:
  void robot_description_param_cb(std::shared_future<std::vector<rclcpp::Parameter>> future);

  std::shared_ptr<rclcpp::AsyncParametersClient> parameters_client_;
  std::string robot_urdf_;

  std::vector<std::string> joint_names_;
  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;

  bool has_effort_states_{true};

  double update_rate_;

  // Kinematics parameters
  std::string base_link_;
  std::string interaction_link_;
  size_t degrees_of_freedom_{1};

  /* Controller Stiffness and Damping */
  Eigen::Matrix6d stiffness_matrix_;
  Eigen::Matrix6d damping_matrix_;

  /* DART members */
  dart::dynamics::SkeletonPtr robot_skeleton_;
  dart::dynamics::BodyNodePtr robot_base_;
  dart::dynamics::BodyNodePtr robot_end_effector_;

  /* Controller Reference Subscriber */
  realtime_tools::RealtimeBuffer<std::shared_ptr<ReferenceType>> rt_reference_ptr_;
  rclcpp::Subscription<ReferenceType>::SharedPtr reference_subscriber_;
};

}  // namespace ros2_impedance_controller

#endif  // ROS2_IMPEDANCE_CONTROLLER__ROS2_IMPEDANCE_CONTROLLER_HPP_
